# Generated by Django 5.2.3 on 2025-06-17 09:20

import src.flatisfaction.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatisfaction', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=src.flatisfaction.users.models.user_avatar_directory_path),
        ),
    ]
