# Generated by Django 5.2.3 on 2025-06-25 09:29

import django.db.models.deletion
import src.flatisfaction.invite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatisfaction', '0003_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('admins', models.ManyToManyField(related_name='admin_flats', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member_flats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=src.flatisfaction.invite.models.generate_random_invite_string, max_length=10)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses', models.IntegerField(default=0)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatisfaction.flat')),
            ],
        ),
    ]
