# Generated by Django 5.2.3 on 2025-07-24 14:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatisfaction', '0004_flat_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='can_member_edit_chores',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(null=True)),
                ('frequency', models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('montly', 'monthly'), ('irregular', 'irregular')])),
                ('frequency_gap', models.IntegerField(default=1)),
                ('weekdays', models.JSONField(default='[]')),
                ('effort', models.IntegerField(default=1)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatisfaction.flat')),
                ('responsible_members', models.ManyToManyField(related_name='responsible_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 7, 24))),
                ('assigned_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_member', to=settings.AUTH_USER_MODEL)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore', to='flatisfaction.chore')),
                ('executor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='flatisfaction.flat')),
            ],
        ),
    ]
